name: VPC Resource - Terraform Destroy
on:
  workflow_dispatch:
    inputs:
      project:
        type: string
        description: None
      env:
        type: string
        description: None
      cidr_block_vpc:
        type: string
        description: None
      cidr_block_pri:
        type: string
        description: None
      cidr_block_pub:
        type: string
        description: None
      enable_dns_support:
        type: boolean
        description: None
      enable_dns_hostnames:
        type: boolean
        description: None
      port_context:
        required: true
        description: >-
          Port's payload, including details for who triggered the action and
          general context (blueprint, run id, etc...)
jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          aws-region: '${{ secrets.AWS_REGION }}'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.6

      - name: Terraform Backend
        id: backend
        env:
          TF_VAR_project:  "${{ github.event.inputs.project }}"
          TF_VAR_env:  "${{ github.event.inputs.env }}"
          TF_VAR_aws_region: "${{ secrets.AWS_REGION }}"
        run: |
          sed -i 's/workspaceName/${{ github.event.inputs.project }}-${{ github.event.inputs.env }}-vpc/g' terraform/config.remote.tfbackend
          sed -i 's/TF_TOKEN/${{ secrets.TF_TOKEN }}/g' terraform/terraformrc
          mv terraform/config.remote.tfbackend terraform/vpc/
          mv terraform/terraformrc ${HOME}/.terraformrc

      - name: Terraform Destroy
        id: destroy
        env:
          TF_VAR_project: "${{ github.event.inputs.project }}"
          TF_VAR_env: "${{ github.event.inputs.env }}"
          TF_VAR_cidr_block_vpc: "${{ github.event.inputs.cidr_block_vpc }}"
          TF_VAR_cidr_block_pri: "${{ github.event.inputs.cidr_block_pri }}"
          TF_VAR_cidr_block_pub: "${{ github.event.inputs.cidr_block_pub }}"
          TF_VAR_enable_dns_support: "${{ github.event.inputs.enable_dns_support }}"
          TF_VAR_enable_dns_hostnames: "${{ github.event.inputs.enable_dns_hostnames }}"
          TF_VAR_aws_region: "${{ secrets.AWS_REGION }}"
        run: |
          cd terraform/vpc/
          terraform init -backend-config=config.remote.tfbackend
          terraform destroy -auto-approve

      - uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: DELETE
          identifier: ${{ github.event.inputs.project }}-${{ github.event.inputs.env }}
          blueprint: VpcResource